### ISSUE TITLE
no active peer to connect to

### ISSUE THREAD

**Issue by harshvardhansharma** [AidosKuneen/aidos-node#2]
hello, my node is not able to connect to any active peers thus failing to sync the chain.
i am not able to call the getBalance or getTransaction commands.

**Comment by Nos-Manus** [comment]
Hello,
Your description is very vague - "can't connect to any peers" like it could be an internet or an server issue. Without a proper technical description (or logs) I won't be able to help. Those commands don't work if the node isn't synced.

**Comment by luoqeng** [comment]
console log
```
2018-11-29 17:00:03,601 INFO [main] com.aidos.ari.Main Welcome to ARI 1.0.1.0
2018-11-29 17:00:03,606 INFO [main] com.aidos.ari.Main com.sanityinc.jargs.CmdLineParser@30ee2816
2018-11-29 17:00:03,607 DEBUG [main] com.aidos.ari.conf.Configuration Setting MESH_RECEIVER_PORT with 14265
2018-11-29 17:00:03,608 INFO [main] com.aidos.ari.Main Peer Discovery enabled. Binding API socket to listen any interface and limiting remote API commands.
2018-11-29 17:00:03,608 DEBUG [main] com.aidos.ari.conf.Configuration Setting API_HOST with 0.0.0.0
2018-11-29 17:00:03,648 INFO [pool-2-thread-2] com.aidos.ari.service.Node Spawning Broadcaster Thread
2018-11-29 17:00:03,649 INFO [pool-2-thread-3] com.aidos.ari.service.Node Spawning Tips Requester Thread
2018-11-29 17:00:03,648 INFO [pool-2-thread-1] com.aidos.ari.service.Node Spawning Receiver Thread
2018-11-29 17:00:03,687 DEBUG [main] com.aidos.ari.service.API Binding JSON-REST API Undertown server on 0.0.0.0:14266
2018-11-29 17:00:03,721 DEBUG [main] org.jboss.logging Logging Provider: org.jboss.logging.Slf4jLoggerProvider
2018-11-29 17:00:03,723 DEBUG [main] io.undertow starting undertow server io.undertow.Undertow@55f616cf
2018-11-29 17:00:03,729 INFO [main] org.xnio XNIO version 3.3.6.Final
2018-11-29 17:00:03,744 INFO [main] org.xnio.nio XNIO NIO Implementation Version 3.3.6.Final
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xnio.nio.NioXnio$2 (file:/home/luoqeng/dev/blockchain/AidosKuneen/ari-1.0.1.0.jar) to constructor sun.nio.ch.EPollSelectorProvider()
WARNING: Please consider reporting this to the maintainers of org.xnio.nio.NioXnio$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-11-29 17:00:03,877 DEBUG [XNIO-1 I/O-1] org.xnio.nio Started channel thread 'XNIO-1 I/O-1', selector sun.nio.ch.EPollSelectorImpl@44f9844d
2018-11-29 17:00:03,877 DEBUG [XNIO-1 I/O-2] org.xnio.nio Started channel thread 'XNIO-1 I/O-2', selector sun.nio.ch.EPollSelectorImpl@6eeb1910
2018-11-29 17:00:03,877 DEBUG [XNIO-1 I/O-3] org.xnio.nio Started channel thread 'XNIO-1 I/O-3', selector sun.nio.ch.EPollSelectorImpl@56740f7b
2018-11-29 17:00:03,878 DEBUG [XNIO-1 I/O-4] org.xnio.nio Started channel thread 'XNIO-1 I/O-4', selector sun.nio.ch.EPollSelectorImpl@2486e83
2018-11-29 17:00:03,879 DEBUG [XNIO-1 I/O-5] org.xnio.nio Started channel thread 'XNIO-1 I/O-5', selector sun.nio.ch.EPollSelectorImpl@25c8fb2b
2018-11-29 17:00:03,879 DEBUG [XNIO-1 I/O-6] org.xnio.nio Started channel thread 'XNIO-1 I/O-6', selector sun.nio.ch.EPollSelectorImpl@211c36ce
2018-11-29 17:00:03,883 DEBUG [XNIO-1 I/O-7] org.xnio.nio Started channel thread 'XNIO-1 I/O-7', selector sun.nio.ch.EPollSelectorImpl@7c0baa8d
2018-11-29 17:00:03,883 DEBUG [XNIO-1 Accept] org.xnio.nio Started channel thread 'XNIO-1 Accept', selector sun.nio.ch.EPollSelectorImpl@49538ddf
2018-11-29 17:00:03,883 DEBUG [XNIO-1 I/O-8] org.xnio.nio Started channel thread 'XNIO-1 I/O-8', selector sun.nio.ch.EPollSelectorImpl@5990dc68
2018-11-29 17:00:03,885 DEBUG [main] io.undertow Configuring listener with protocol HTTP for interface 0.0.0.0 and port 14266
2018-11-29 17:00:05,182 DEBUG [main] com.jayway.jsonpath.internal.path.CompiledPath Evaluating path: $['ip']
2018-11-29 17:00:05,185 DEBUG [main] com.aidos.ari.service.PD IP set to: 68.168.128.62 (ipv4)
2018-11-29 17:00:05,186 DEBUG [main] com.aidos.ari.service.PD Peer 2a01:4f8:c0c:734:0:0:0:2 not reachable.
2018-11-29 17:00:06,321 DEBUG [main] com.aidos.ari.service.PD Seed 51.255.44.96 is other ipv4.
2018-11-29 17:00:06,322 INFO [main] com.aidos.ari.service.PD Retrieving Seed from DNS success. (ipv4)
2018-11-29 17:00:06,765 DEBUG [main] com.aidos.ari.service.PD Can't connect to API on address: 51.255.44.96
2018-11-29 17:00:06,769 ERROR [main] com.aidos.ari.Main Exception during Aidos Node init:
java.lang.Exception: Can't connect to any nodes.
        at com.aidos.ari.service.PD.init(PD.java:157) ~[ari-1.0.1.0.jar:na]
        at com.aidos.ari.Main.main(Main.java:40) ~[ari-1.0.1.0.jar:na]
2018-11-29 17:00:06,771 INFO [Shutdown Hook] com.aidos.ari.Main Shutting down AIDOS node, please hold tight...
2018-11-29 17:00:06,771 INFO [Shutdown Hook] com.aidos.ari.service.PD No Peerlist created since Peers were empty.
2018-11-29 17:00:12,773 DEBUG [Shutdown Hook] io.undertow stopping undertow server io.undertow.Undertow@55f616cf
2018-11-29 17:00:12,853 INFO [pool-2-thread-2] com.aidos.ari.service.Node Shutting down Broadcaster Thread
2018-11-29 17:00:13,656 INFO [pool-2-thread-3] com.aidos.ari.service.Node Shutting down Requester Thread
2018-11-29 17:00:18,785 INFO [Shutdown Hook] com.aidos.ari.service.storage.StorageTransactions Flushing transactions chunk #0
2018-11-29 17:00:18,786 INFO [Shutdown Hook] com.aidos.ari.service.storage.StorageTransactions Flushing transactions chunk #1
2018-11-29 17:00:18,787 INFO [Shutdown Hook] com.aidos.ari.service.storage.StorageBundle Flushing bundles chunk #0
2018-11-29 17:00:18,787 INFO [Shutdown Hook] com.aidos.ari.service.storage.StorageBundle Flushing bundles chunk #1
2018-11-29 17:00:18,788 INFO [Shutdown Hook] com.aidos.ari.service.storage.StorageAddresses Flushing addresses chunk #0
2018-11-29 17:00:18,789 INFO [Shutdown Hook] com.aidos.ari.service.storage.StorageAddresses Flushing addresses chunk #1
2018-11-29 17:00:18,790 INFO [Shutdown Hook] com.aidos.ari.service.storage.StorageTags Flushing tags chunk #0
2018-11-29 17:00:18,790 INFO [Shutdown Hook] com.aidos.ari.service.storage.StorageTags Flushing tags chunk #1
2018-11-29 17:00:18,791 INFO [Shutdown Hook] com.aidos.ari.service.storage.StorageApprovers Flushing approvers chunk #0
2018-11-29 17:00:18,791 INFO [Shutdown Hook] com.aidos.ari.service.storage.StorageApprovers Flushing approvers chunk #1
2018-11-29 17:00:18,793 INFO [Shutdown Hook] com.aidos.ari.service.storage.Storage DB successfully flushed
```

**Comment by Nos-Manus** [comment]
Your node is trying to connect to an offline node even though this is prevented by an simple online check in the [code](https://github.com/AidosKuneen/aidos-node/blob/master/src/main/java/com/aidos/ari/service/PD.java#L204). So it seems to be related to an connection issue / setting by your server. Maybe try it on another server, since I just bootstrapped a node successfully without any issue with the same settings. If the same still happens please post the logs again to evaluate if the same thing happens again (which is unlikely).

**Comment by luoqeng** [comment]
mvn package && java -jar target/ari-1.0.1.0.jar -r 14265 -p
```
2018-11-29 21:04:38,872 INFO [main] com.aidos.ari.Main Welcome to ARI 1.0.1.0
2018-11-29 21:04:38,879 INFO [main] com.aidos.ari.Main com.sanityinc.jargs.CmdLineParser@30ee2816
2018-11-29 21:04:38,880 DEBUG [main] com.aidos.ari.conf.Configuration Setting MESH_RECEIVER_PORT with 14265
2018-11-29 21:04:38,880 INFO [main] com.aidos.ari.Main Peer Discovery enabled. Binding API socket to listen any interface and limiting remote API commands.
2018-11-29 21:04:38,880 DEBUG [main] com.aidos.ari.conf.Configuration Setting API_HOST with 0.0.0.0
2018-11-29 21:04:38,900 INFO [pool-2-thread-2] com.aidos.ari.service.Node Spawning Broadcaster Thread
2018-11-29 21:04:38,901 INFO [pool-2-thread-1] com.aidos.ari.service.Node Spawning Receiver Thread
2018-11-29 21:04:38,903 INFO [pool-2-thread-3] com.aidos.ari.service.Node Spawning Tips Requester Thread
2018-11-29 21:04:38,950 DEBUG [main] com.aidos.ari.service.API Binding JSON-REST API Undertown server on 0.0.0.0:14266
2018-11-29 21:04:38,991 DEBUG [main] org.jboss.logging Logging Provider: org.jboss.logging.Slf4jLoggerProvider
2018-11-29 21:04:38,993 DEBUG [main] io.undertow starting undertow server io.undertow.Undertow@55f616cf
2018-11-29 21:04:39,001 INFO [main] org.xnio XNIO version 3.3.6.Final
2018-11-29 21:04:39,018 INFO [main] org.xnio.nio XNIO NIO Implementation Version 3.3.6.Final
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xnio.nio.NioXnio$2 (file:/home/luoqeng/dev/blockchain/AidosKuneen/aidos-node/target/ari-1.0.1.0.jar) to constructor sun.nio.ch.EPollSelectorProvider()
WARNING: Please consider reporting this to the maintainers of org.xnio.nio.NioXnio$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-11-29 21:04:39,172 DEBUG [XNIO-1 I/O-1] org.xnio.nio Started channel thread 'XNIO-1 I/O-1', selector sun.nio.ch.EPollSelectorImpl@3c516077
2018-11-29 21:04:39,173 DEBUG [XNIO-1 I/O-2] org.xnio.nio Started channel thread 'XNIO-1 I/O-2', selector sun.nio.ch.EPollSelectorImpl@44f9844d
2018-11-29 21:04:39,173 DEBUG [XNIO-1 I/O-3] org.xnio.nio Started channel thread 'XNIO-1 I/O-3', selector sun.nio.ch.EPollSelectorImpl@6eeb1910
2018-11-29 21:04:39,174 DEBUG [XNIO-1 I/O-4] org.xnio.nio Started channel thread 'XNIO-1 I/O-4', selector sun.nio.ch.EPollSelectorImpl@56740f7b
2018-11-29 21:04:39,174 DEBUG [XNIO-1 I/O-5] org.xnio.nio Started channel thread 'XNIO-1 I/O-5', selector sun.nio.ch.EPollSelectorImpl@648fccce
2018-11-29 21:04:39,175 DEBUG [XNIO-1 I/O-6] org.xnio.nio Started channel thread 'XNIO-1 I/O-6', selector sun.nio.ch.EPollSelectorImpl@6770ab1c
2018-11-29 21:04:39,180 DEBUG [XNIO-1 I/O-7] org.xnio.nio Started channel thread 'XNIO-1 I/O-7', selector sun.nio.ch.EPollSelectorImpl@25c8fb2b
2018-11-29 21:04:39,180 DEBUG [XNIO-1 Accept] org.xnio.nio Started channel thread 'XNIO-1 Accept', selector sun.nio.ch.EPollSelectorImpl@7c0baa8d
2018-11-29 21:04:39,180 DEBUG [XNIO-1 I/O-8] org.xnio.nio Started channel thread 'XNIO-1 I/O-8', selector sun.nio.ch.EPollSelectorImpl@211c36ce
2018-11-29 21:04:39,183 DEBUG [main] io.undertow Configuring listener with protocol HTTP for interface 0.0.0.0 and port 14266
2018-11-29 21:04:39,944 DEBUG [main] com.jayway.jsonpath.internal.path.CompiledPath Evaluating path: $['ip']
2018-11-29 21:04:39,947 DEBUG [main] com.aidos.ari.service.PD IP set to: 68.168.128.62 (ipv4)
2018-11-29 21:04:39,948 DEBUG [main] com.aidos.ari.service.PD Peer 2a01:4f8:c0c:734:0:0:0:2 not reachable.
2018-11-29 21:04:40,057 DEBUG [main] com.aidos.ari.service.PD Seed 88.99.175.110 is other ipv4.
2018-11-29 21:04:40,058 INFO [main] com.aidos.ari.service.PD Retrieving Seed from DNS success. (ipv4)
2018-11-29 21:04:40,701 DEBUG [main] com.jayway.jsonpath.internal.path.CompiledPath Evaluating path: $['ip']
2018-11-29 21:04:40,702 DEBUG [main] com.aidos.ari.service.PD Adding 88.99.175.110 to Node Peers. Success: true
2018-11-29 21:04:40,703 INFO [main] com.aidos.ari.Main Aidos Node initialised correctly.
2018-11-29 21:04:40,703 INFO [pool-3-thread-1] com.aidos.ari.service.PD Spawning PD Thread
2018-11-29 21:04:41,547 DEBUG [pool-6-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-29 21:04:41,548 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Iteration Peer: 88.99.175.110
2018-11-29 21:04:42,200 DEBUG [pool-3-thread-1] com.jayway.jsonpath.internal.path.CompiledPath Evaluating path: $['peerlist']
2018-11-29 21:04:42,794 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 158.69.218.134 Server returned HTTP response code: 400 for URL: http://158.69.218.134:14266
2018-11-29 21:04:43,645 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 78.46.250.91 Server returned HTTP response code: 400 for URL: http://78.46.250.91:14266
2018-11-29 21:04:43,652 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Iteration Peer: 158.69.218.134
2018-11-29 21:04:44,146 DEBUG [pool-3-thread-1] com.jayway.jsonpath.internal.path.CompiledPath Evaluating path: $['peerlist']
2018-11-29 21:04:44,946 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 94.130.160.176 Server returned HTTP response code: 400 for URL: http://94.130.160.176:14266
2018-11-29 21:04:45,754 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 78.47.29.65 Server returned HTTP response code: 400 for URL: http://78.47.29.65:14266
2018-11-29 21:04:46,562 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 144.76.182.217 Server returned HTTP response code: 400 for URL: http://144.76.182.217:14266
2018-11-29 21:04:47,431 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 78.46.193.200 Server returned HTTP response code: 400 for URL: http://78.46.193.200:14266
2018-11-29 21:04:47,432 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Iteration Peer: 78.46.250.91
2018-11-29 21:04:48,093 DEBUG [pool-3-thread-1] com.jayway.jsonpath.internal.path.CompiledPath Evaluating path: $['peerlist']
2018-11-29 21:04:48,095 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Iteration Peer: 94.130.160.176
2018-11-29 21:04:48,749 DEBUG [pool-3-thread-1] com.jayway.jsonpath.internal.path.CompiledPath Evaluating path: $['peerlist']
2018-11-29 21:04:51,758 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 110.234.0.181 Read timed out
2018-11-29 21:04:51,759 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Iteration Peer: 78.47.29.65
2018-11-29 21:04:52,370 DEBUG [pool-3-thread-1] com.jayway.jsonpath.internal.path.CompiledPath Evaluating path: $['peerlist']
2018-11-29 21:04:52,371 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Iteration Peer: 144.76.182.217
2018-11-29 21:04:53,479 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 13.251.102.241 Unexpected end of file from server
2018-11-29 21:04:53,479 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Iteration Peer: 78.46.193.200
2018-11-29 21:04:54,131 DEBUG [pool-3-thread-1] com.jayway.jsonpath.internal.path.CompiledPath Evaluating path: $['peerlist']
2018-11-29 21:04:54,132 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Iteration Peer: 110.234.0.181
2018-11-29 21:04:54,816 DEBUG [pool-3-thread-1] com.jayway.jsonpath.internal.path.CompiledPath Evaluating path: $['peerlist']
2018-11-29 21:04:55,258 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 51.255.44.96 Unexpected end of file from server
2018-11-29 21:04:55,702 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 106.10.54.19 Unexpected end of file from server
2018-11-29 21:04:55,702 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Iteration Peer: 13.251.102.241
2018-11-29 21:04:56,228 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Can't connect to API on address: 13.251.102.241
2018-11-29 21:04:56,228 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Iteration Peer: 51.255.44.96
2018-11-29 21:04:56,680 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Can't connect to API on address: 51.255.44.96
2018-11-29 21:04:56,680 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Iteration Peer: 106.10.54.19
2018-11-29 21:04:57,122 DEBUG [pool-3-thread-1] com.aidos.ari.service.PD Can't connect to API on address: 106.10.54.19
2018-11-29 21:10:58,015 DEBUG [pool-53-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-29 21:17:01,027 DEBUG [pool-54-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Read timed out
2018-11-29 21:56:14,164 DEBUG [pool-55-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-29 22:09:28,201 DEBUG [pool-56-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 00:15:27,121 DEBUG [pool-57-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 00:21:28,100 DEBUG [pool-58-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 00:27:28,935 DEBUG [pool-59-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 00:33:29,751 DEBUG [pool-60-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 00:39:30,547 DEBUG [pool-61-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 00:45:31,340 DEBUG [pool-62-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 01:41:35,727 DEBUG [pool-63-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 01:47:36,748 DEBUG [pool-64-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 01:53:37,720 DEBUG [pool-65-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 01:59:38,561 DEBUG [pool-66-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 02:05:39,600 DEBUG [pool-67-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 02:11:40,565 DEBUG [pool-68-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 02:50:10,971 DEBUG [pool-69-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 02:56:11,952 DEBUG [pool-70-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 03:02:12,829 DEBUG [pool-71-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 05:08:11,997 DEBUG [pool-72-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 05:14:13,161 DEBUG [pool-73-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 07:20:13,082 DEBUG [pool-74-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 07:26:14,212 DEBUG [pool-75-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 07:32:15,350 DEBUG [pool-76-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 09:38:14,774 DEBUG [pool-77-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
2018-11-30 09:46:21,872 DEBUG [pool-78-thread-1] com.aidos.ari.service.PD Failure pushing Peer address to: 88.99.175.110 Server returned HTTP response code: 400 for URL: http://88.99.175.110:14266
```

**Comment by Nos-Manus** [comment]
Your server seems to have a problem issuing HTTP requests. Please use `curl -d '{"command": "getNodeInfo"}' -H 'Content-Type: application/json' http://78.46.193.200:14266
` and see what the output of that is. If this doesn't work your problems are related to your server and not to our code.

**Comment by luoqeng** [comment]
```
curl -d '{"command": "getNodeInfo"}' -H 'Content-Type: application/json' http://78.46.193.200:14266 | json_pp
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_CTYPE = "UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   590  100   564  100    26    855     39 --:--:-- --:--:-- --:--:--   893
{
   "appName" : "ARI",
   "appVersion" : "1.0.1.0",
   "duration" : 15,
   "jreAvailableProcessors" : 4,
   "jreFreeMemory" : 433801624,
   "jreMaxMemory" : 3739746304,
   "jreTotalMemory" : 1360003072,
   "jreVersion" : "1.8.0_191",
   "latestMilestone" : "RFLUDRGZ9RWJYDMBKIZKVZO9TDBEIJACNIHRSEJWYWZMSDSVEMTKUYFQIRMNXVHGHYFIVZQYXOJ999999",
   "latestMilestoneIndex" : 262997,
   "latestSolidSubmeshMilestone" : "RFLUDRGZ9RWJYDMBKIZKVZO9TDBEIJACNIHRSEJWYWZMSDSVEMTKUYFQIRMNXVHGHYFIVZQYXOJ999999",
   "latestSolidSubmeshMilestoneIndex" : 262997,
   "packetsQueueSize" : 32,
   "peers" : 7,
   "time" : 1543824258804,
   "tips" : 413,
   "transactionsToRequest" : 0
}
```
